### ISSUE TITLE
have error message "Missing filters: lzf"

### ISSUE THREAD

**Issue by alex46015** [grimbough/rhdf5#121]
I installed rhdf5filters, I used h5read or H5Fopen to access to dataset by $ &,
it always show
Error: unable to read dataset.
not all required filters available
Missing filters: lzf
h5checktype() . H5Identifuer not valid

Do you have clue for this problem?

Thanks

**Comment by grimbough** [comment]
Can you provide the output of `sessionInfo()`?  The LZF filter isn't available in some early versions of rhdf5filters.

You can also make sure that the filter plugin location is known by running `Sys.getenv("HDF5_PLUGIN_PATH")` and check the contents with `list.files(Sys.getenv("HDF5_PLUGIN_PATH"))`
