### ISSUE TITLE
Binaries for arm64?

### ISSUE THREAD

**Issue by jemorlanes** [grimbough/rhdf5#129]
Hello!

I have a quick question for you guys! I am working on a M1 Macbook. When trying to install the package from Bioconductor, I get the following error:
`checking build system type... Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ../config/config.sub arm64-apple-darwin20.0.0 failed`

Are you planning on putting out a release for this machine?

Thank you for your help!

**Comment by grimbough** [comment]
This issue was being tracked in https://github.com/grimbough/Rhdf5lib/issues/54 and should have been fixed in https://github.com/grimbough/Rhdf5lib/commit/0a56f0439a0783deff92657ebbe81258d28af897
