### ISSUE TITLE
"rhdf5filters.so’ not found when install 'rhdf5' package in R 4.2.2

### ISSUE THREAD

**Issue by muyixu** [grimbough/rhdf5#133]
When I install the package 'rhdf5', error occurs like this:
![image](https://github.com/grimbough/rhdf5/assets/38967248/608c44f9-d55a-4b62-9b8e-91dbde04f76a)
How to solve this problem?

**Comment by grimbough** [comment]
Have you tried re-installling `rhdf5filters`? This should install both packages:

```r
BiocManager::install(c("rhdf5filters", "rhdf5"), force = TRUE)
```

**Comment by muyixu** [comment]
It works!! Thank you for your help!

**Comment by grimbough** [comment]
Great, thanks for reporting back!
